name: Deploy to Windows Server (P10113)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on self-hosted Windows runner
    runs-on: [self-hosted, P10113]  # 使用你的自註冊 runner

    steps:
      - name: Change to project directory and deploy
        run: |
          cd /d "D:\apacheTest\ServerSample\web\node\ERP_system_backend"
          git pull
          npm install
